---

- hosts: localhost
  become: yes
  vars:
    oscap_profile: xccdf_mil.disa.stig_profile_MAC-1_Public
    oscap_content: /home/mradecke/Downloads/U_RHEL_8_V1R10_STIG_SCAP_1-2_Benchmark.xml
    results_dir: /home/mradecke/openscap
  tasks:
  - name: Install OpenSCAP Scanner and SCAP-Security-Guide
    yum:
      name:
      - openscap*
      - scap-security-guide
      state: latest


  # The following tasks will create scan results and a scan report.
  # The scan results should be checked before running the playbook that is generated
  # so that STIG items that might potentially disrupt functionality are commented out
  # or adjusted for the system.


  - block:
    - name: Run OpenSCAP
      command: oscap xccdf eval \
        --profile {{ oscap_profile }} \
        --results-arf /tmp/scan-xccdf-results.xml \
        --report /tmp/oscap-report.html \
        --fetch-remote-resources
        {{ oscap_content }}
      register: scan_results
      failed_when: scan_results.rc == 1

    - name: Generate playbook from scan results
      command: oscap xccdf generate fix \
        --fix-type ansible \
        --result-id {{ oscap_profile }} \
        --output {{ results_dir }}/stig-playbook-result.yml /tmp/scan-xccdf-results.xml

    - name: Download report
      fetch:
        src: /tmp/oscap-report.html
        dest: '{{ results_dir }}/{{ inventory_hostname }}_report.html'
        flat: yes

    - name: Download results
      fetch:
        src: /tmp/scan-xccdf-results.xml
        dest: '{{ results_dir }}/{{ inventory_hostname }}_results.xml'
        flat: yes
